import { lazy } from 'react';

const Icons = {
  Menu: lazy(() => import('@mui/icons-material/Menu')),
  CloseMenu: lazy(() => import('@mui/icons-material/RemoveOutlined')),
  People: lazy(() => import('@mui/icons-material/People')),
  Paragliding: lazy(() => import('@mui/icons-material/Paragliding')),
  Inventory: lazy(() => import('@mui/icons-material/Inventory')),
  Signature: lazy(() => import('@mui/icons-material/Draw')),
  ArrowLeft: lazy(() => import('@mui/icons-material/ArrowBackIosNewOutlined')),
  ArrowRight: lazy(() => import('@mui/icons-material/ArrowForwardIosOutlined')),
  Gift: lazy(() => import('@mui/icons-material/RedeemOutlined')),
  User: lazy(() => import('@mui/icons-material/AccountCircle')),
  Logout: lazy(() => import('@mui/icons-material/PowerSettingsNew')),
  Profile: lazy(() => import('@mui/icons-material/PermIdentity')),
  Search: lazy(() => import('@mui/icons-material/Search')),
  Sort: lazy(() => import('@mui/icons-material/SortRounded')),
  Add: lazy(() => import('@mui/icons-material/Add')),
  Department: lazy(() => import('@mui/icons-material/CorporateFare')),
  Home: lazy(() => import('@mui/icons-material/HomeRounded')),
  Close: lazy(() => import('@mui/icons-material/Close')),
  Mobile: lazy(() => import('@mui/icons-material/PhoneAndroid')),
  Email: lazy(() => import('@mui/icons-material/Email')),
  Numbers: lazy(() => import('@mui/icons-material/Numbers')),
  ErrorOutline: lazy(() => import('@mui/icons-material/ErrorOutline')),
  Info: lazy(() => import('@mui/icons-material/Info')),
  Warning: lazy(() => import('@mui/icons-material/WarningAmber')),
  Success: lazy(() => import('@mui/icons-material/CheckCircleOutlineRounded')),
  Error: lazy(() => import('@mui/icons-material/ReportGmailerrorred')),
  Abc: lazy(() => import('@mui/icons-material/Abc')),
  Edit: lazy(() => import('@mui/icons-material/EditRounded')),
  Save: lazy(() => import('@mui/icons-material/SaveRounded')),
  Grid: lazy(() => import('@mui/icons-material/GridOnRounded')),
  Columns: lazy(() => import('@mui/icons-material/ViewColumnOutlined')),
  Receive: lazy(() => import('@mui/icons-material/CallReceived')),
  Exchange: lazy(() => import('@mui/icons-material/SwapHoriz')),
  Removal: lazy(() => import('@mui/icons-material/PlaylistRemove')),
  Equipment: lazy(() => import('@mui/icons-material/HomeRepairService')),
};

export default Icons;
